name: Send Data to Email and update README.md

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

permissions:
  contents: write

jobs:
  send-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Update README.md and send email
        run: npm run send-data

      - name: Configure Git
        run: |
          git config user.name "solidsnk86"
          git config user.email "calcagni.gabriel86@gmail.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖[neoBot] Updated data and sended email"
          git push origin master